### ISSUE TITLE
ValueError: num_samples should be a positive integer value, but got num_samples=0

### ISSUE THREAD

**Issue by dipakmeher** [JoeYing1019/MMSD2.0#1]
Hi,
I'm trying to implement your code, and I'm encountering this error that I am not able to resolve. 

Traceback (most recent call last):
  File "/home/dmeher/ANLP_Project/MMSD20/src/main.py", line 95, in <module>
    main()
  File "/home/dmeher/ANLP_Project/MMSD20/src/main.py", line 90, in main
    train(args, model, device, train_data, dev_data, test_data, processor)
  File "/home/dmeher/ANLP_Project/MMSD20/src/train.py", line 21, in train
    train_loader = DataLoader(dataset=train_data,
  File "/opt/sw/spack/apps/linux-rhel8-x86_64_v2/gcc-10.3.0/python-3.9.9-jh/lib/python3.9/site-packages/torch/utils/data/dataloader.py", line 353, in __init__
    sampler = RandomSampler(dataset, generator=generator)  # type: ignore[arg-type]
  File "/opt/sw/spack/apps/linux-rhel8-x86_64_v2/gcc-10.3.0/python-3.9.9-jh/lib/python3.9/site-packages/torch/utils/data/sampler.py", line 107, in __init__
    raise ValueError("num_samples should be a positive integer "
ValueError: num_samples should be a positive integer value, but got num_samples=0

I just executed this command and got error:
python3 main.py --model MV_CLIP --text_name text_json_final --weight_decay 0.05 --train_batch_size 32 --dev_batch_size 32 --learning_rate 5e-4 --clip_learning_rate 1e-6 --num_train_epochs 10 --layers 3 --max_grad_norm 5 --dropout_rate 0.1 --optimizer_name adam --text_size 512 --image_size 768 --warmup_proportion 0.2 --device 0 

Any help would be greatly appreciated. Thanks.

**Comment by dipakmeher** [comment]
Issue Resolved!! I made a mistake in the file path. As soon as I corrected it, the code is running.

**Comment by Aichiniuroumian** [comment]
> 0/src/train.py", line 21, in train
> train_loader = DataLoader(dataset=train_data,

Hi~ I also encountered this problem, but I found through the debug way that the path is correct, can read the data, but the final return data_set dictionary is empty, may I ask you to modify which place to solve it? I would be grateful if you could reply in time!
Have a nice day~😊
